name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble Ogg debug and release builds
      run: ./gradlew :ogg:assemble
    - name: Publish Ogg to local Maven repository
      run: ./gradlew :ogg:publishAllPublicationsToMavenLocal
    - name: Assemble Vorbis debug and release builds
      run: ./gradlew :vorbis:assemble
    - name: Publish Vorbis to local Maven repository
      run: ./gradlew :vorbis:publishAllPublicationsToMavenLocal
